# common.yaml - Sensors, Scripts, Global Variables
# Screen-saver dims backlight after 5 min idle, touch wakes (handled in device.yaml)

time:
  - platform: homeassistant
    id: ha_time

globals:
  - id: entered_code
    type: std::string
    initial_value: '""'

  - id: pending_action
    type: std::string
    initial_value: '""'

  # Tracks seconds since last touch for screen-saver
  - id: idle_seconds
    type: int
    initial_value: '0'

# Screen saver - pause LVGL and dim backlight after 5 minutes of inactivity
# Touch screen to wake (handled by touchscreen on_touch in device.yaml).
interval:
  - interval: 1s
    then:
      - lambda: |-
          id(idle_seconds) += 1;
      - if:
          condition:
            lambda: 'return id(idle_seconds) >= 300;'
          then:
            - lambda: 'id(idle_seconds) = 0;'
            - lvgl.pause:
            - light.turn_off: display_backlight

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_strength
    update_interval: 60s
    internal: true

  - platform: homeassistant
    id: outside_temp_sensor
    entity_id: ${outside_temp}
    internal: true

  - platform: homeassistant
    id: alarm_delay_time
    entity_id: ${alarm_panel}
    attribute: delay
    internal: true

  - platform: homeassistant
    id: inside_temp_sensor
    entity_id: ${inside_temp}
    internal: true

text_sensor:
  - platform: homeassistant
    id: alarm_state
    entity_id: ${alarm_panel}
    internal: true

binary_sensor:
  # Light entities: HA state is "on"/"off" which maps directly to binary_sensor true/false
  - platform: homeassistant
    id: living_room_light_state
    entity_id: ${living_room_light}
    internal: true

  # Lock entities: HA state is "locked"/"unlocked" — need publish_initial_state
  - platform: homeassistant
    id: front_door_locked
    entity_id: ${front_door_lock}
    internal: true

  - platform: homeassistant
    id: garage_door_open
    entity_id: ${south_garage_sensor}
    internal: true

  - platform: homeassistant
    id: back_door_sensor_open
    entity_id: ${back_door_sensor}
    internal: true

  - platform: homeassistant
    id: front_door_sensor_open
    entity_id: ${front_door_sensor}
    internal: true

  - platform: homeassistant
    id: back_door_locked
    entity_id: ${back_door_lock}
    internal: true

  - platform: homeassistant
    id: kitchen_light_state
    entity_id: ${kitchen_light}
    internal: true

  - platform: homeassistant
    id: outdoor_light_state
    entity_id: ${outdoor_light}
    internal: true

script:
  - id: arm_away_script
    then:
      - homeassistant.service:
          service: alarm_control_panel.alarm_arm_away
          data:
            entity_id: ${alarm_panel}
            code: !lambda 'return id(entered_code);'

  - id: arm_home_script
    then:
      - homeassistant.service:
          service: alarm_control_panel.alarm_arm_home
          data:
            entity_id: ${alarm_panel}
            code: !lambda 'return id(entered_code);'

  - id: arm_night_script
    then:
      - homeassistant.service:
          service: alarm_control_panel.alarm_arm_night
          data:
            entity_id: ${alarm_panel}
            code: !lambda 'return id(entered_code);'

  - id: arm_vacation_script
    then:
      - homeassistant.service:
          service: alarm_control_panel.alarm_arm_vacation
          data:
            entity_id: ${alarm_panel}
            code: !lambda 'return id(entered_code);'

  - id: arm_custom_bypass_script
    then:
      - homeassistant.service:
          service: alarm_control_panel.alarm_arm_custom_bypass
          data:
            entity_id: ${alarm_panel}
            code: !lambda 'return id(entered_code);'

  - id: disarm_script
    then:
      - homeassistant.service:
          service: alarm_control_panel.alarm_disarm
          data:
            entity_id: ${alarm_panel}
            code: !lambda 'return id(entered_code);'
