# ESPHome Rental Property Display - Waveshare ESP32-S3-Touch-LCD-7B
# 1024x600 landscape | Dark theme | Alarmo integration
# https://github.com/trentrae/esphome-rental-display
#
# This file is the LOCAL entry point for direct flashing (non-remote-package).
# For remote package usage, see _package.yaml.

esphome:
  name: rental-display-7b
  friendly_name: "Rental Property Display 7B"

packages:
  - !include device.yaml
  - !include common.yaml
  - !include substitutions.yaml
  - !include layouts/main.yaml
  - !include layouts/fonts.yaml
  - !include layouts/colors.yaml
  - !include layouts/update_intervals_pkg.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Rental Display Fallback"
    password: !secret wifi_password

api:
  encryption:
    key: !secret api_encryption_key

# Pause LVGL during OTA to prevent corrupted frames and improve transfer speed
ota:
  - platform: esphome
    password: !secret ota_password
    on_begin:
      then:
        - lvgl.pause:

logger:
  level: INFO

web_server:
  port: 80
